// flow-eda-react/src/pages/FlowEditor/ToolBar/index.tsx
import React, { useState } from 'react';
import { message, Tooltip } from 'antd';
import ConfirmModal from '@/components/ConfirmModal';
import IconFont from '@/components/IconFont';
import './index.less';

const ToolBar: React.FC<{
  status: string;
  copyNode: () => void;
  pasteNode: () => void;
  saveData: () => void;
  deleteNode: () => void;
  executeFlow: () => void;
  stopFlow: () => void;
  zoomNode: (command: string) => void;
  showLogs: (show: boolean) => void;
}> = (props) => {
  const [seeLog, setSeeLog] = useState<string>('查看日志');
  const [openLog, setOpenLog] = useState<boolean>(false);
  const iconStyle = { width: '18px', height: '18px' };

  const handle = (command: string) => {
    if (command.startsWith('zoom')) {
      props.zoomNode(command.split('-')[1]);
    } else if (command === 'logs') {
      if (openLog) {
        props.showLogs(false);
        setSeeLog('查看日志');
      } else {
        props.showLogs(true);
        setSeeLog('关闭日志');
      }
      setOpenLog(!openLog);
    } else if (command === 'save') {
      props.saveData();
      message.success('保存成功');
    } else if (command === 'copy') {
      props.copyNode();
    } else if (command === 'paste') {
      props.pasteNode();
    } else if (command === 'del') {
      props.deleteNode();
    }
  };

  return (
    <div className="toolbar">
      <Tooltip title={seeLog} placement="bottom">
        <span className="command" onClick={() => handle('logs')}>
          <IconFont type="icon-lx-logs" style={iconStyle} />
        </span>
      </Tooltip>
      <span className="separator" />
      <Tooltip title="保存" placement="bottom">
        <span className="command" onClick={() => handle('save')}>
          <IconFont type="icon-lx-save" style={iconStyle} />
        </span>
      </Tooltip>
      {props.status !== 'RUNNING' && (
        <ConfirmModal
          key="run"
          title="确认运行本流程？这将会保存本流程并覆盖之前的数据"
          danger={false}
          onConfirm={async () => await props.executeFlow()}
        >
          <Tooltip title="运行" placement="bottom">
            <span className="command">
              <IconFont type="icon-lx-run" style={iconStyle} />
            </span>
          </Tooltip>
        </ConfirmModal>
      )}
      {props.status === 'RUNNING' && (
        <ConfirmModal
          key="stop"
          title="确认停止运行？这将会立即停止本流程的运行"
          danger={false}
          onConfirm={async () => await props.stopFlow()}
        >
          <Tooltip title="停止" placement="bottom">
            <span className="command">
              <IconFont type="icon-lx-stop" style={iconStyle} />
            </span>
          </Tooltip>
        </ConfirmModal>
      )}
      <span className="separator" />
      <Tooltip title="复制" placement="bottom">
        <span className="command" onClick={() => handle('copy')}>
          <IconFont type="icon-lx-copy" style={iconStyle} />
        </span>
      </Tooltip>
      <Tooltip title="粘贴" placement="bottom">
        <span className="command" onClick={() => handle('paste')}>
          <IconFont type="icon-lx-paste" style={iconStyle} />
        </span>
      </Tooltip>
      <Tooltip title="删除" placement="bottom">
        <span className="command" onClick={() => handle('del')}>
          <IconFont type="icon-lx-delete" style={iconStyle} />
        </span>
      </Tooltip>
      <span className="separator" />
      <Tooltip title="放大" placement="bottom">
        <span className="command" onClick={() => handle('zoom-in')}>
          <IconFont type="icon-lx-zoomIn" style={iconStyle} />
        </span>
      </Tooltip>
      <Tooltip title="缩小" placement="bottom">
        <span className="command" onClick={() => handle('zoom-out')}>
          <IconFont type="icon-lx-zoomOut" style={iconStyle} />
        </span>
      </Tooltip>
      <span className="separator" />
      <Tooltip title="全屏" placement="bottom">
        <span className="command" onClick={() => handle('zoom-full')}>
          <IconFont type="icon-lx-zoomFull" style={iconStyle} />
        </span>
      </Tooltip>
      <Tooltip title="重置" placement="bottom">
        <span className="command" onClick={() => handle('zoom-reset')}>
          <IconFont type="icon-lx-zoomReset" style={iconStyle} />
        </span>
      </Tooltip>
    </div>
  );
};

export default ToolBar;

// flow-eda-vue/src/components/editor/Toolbar.vue
<template>
  <div class="toolbar">
    <span class="separator"/>
    <el-tooltip content="保存" placement="bottom">
      <span class="command" @click="handle('save')">
      <span class="icon-lx-save"/>
      </span>
    </el-tooltip>
    <el-tooltip content="运行" placement="bottom">
      <span class="command" @click="handle('run')">
      <span class="icon-lx-run"/>
      </span>
    </el-tooltip>
    <el-tooltip content="停止" placement="bottom">
      <span class="command" @click="handle('stop')">
      <span class="icon-lx-run"/>
      </span>
    </el-tooltip>
    <span class="separator"/>
    <el-tooltip content="复制" placement="bottom">
      <span class="command" @click="handle('copy')">
      <span class="icon-lx-copy"/>
      </span>
    </el-tooltip>
    <el-tooltip content="粘贴" placement="bottom">
      <span class="command" @click="handle('paste')">
      <span class="icon-lx-paste"/>
      </span>
    </el-tooltip>
    <el-tooltip content="删除" placement="bottom">
      <span class="command" @click="handle('del')">
      <span class="icon-lx-delete"/>
      </span>
    </el-tooltip>
    <span class="separator"/>
    <el-tooltip content="放大" placement="bottom">
      <span class="command" @click="handle('zoom-in')">
      <span class="icon-lx-zoomIn"/>
      </span>
    </el-tooltip>
    <el-tooltip content="缩小" placement="bottom">
      <span class="command" @click="handle('zoom-out')">
      <span class="icon-lx-zoomOut"/>
      </span>
    </el-tooltip>
    <span class="separator"/>
    <el-tooltip content="全屏" placement="bottom">
      <span class="command" @click="handle('zoom-full')">
      <span class="icon-lx-zoomFull"/>
      </span>
    </el-tooltip>
    <el-tooltip content="重置" placement="bottom">
      <span class="command" @click="handle('zoom-reset')">
      <span class="icon-lx-zoomReset"/>
      </span>
    </el-tooltip>
    <span class="separator"/>
  </div>
</template>

<script>
import {ElMessage, ElMessageBox} from "element-plus";

export default {
  name: "Toolbar",
  setup(props, context) {

    const run = () => {
      ElMessageBox.confirm("确认运行本流程？这将会保存本流程并覆盖之前的数据", "提示", {
        type: "warning",
      }).then(() => {
        context.emit("executeFlow");
      }).catch(() => {
      });
    };

    const stop = () => {
      ElMessageBox.confirm("确认停止运行？这将会立即停止本流程的运行", "提示", {
        type: "warning",
      }).then(() => {
        context.emit("stopFlow");
      }).catch(() => {
      });
    };

    const handle = (command) => {
      if (command.startsWith("zoom")) {
        context.emit("zoomNode", command.split('-')[1]);
      } else if (command === "save") {
        context.emit("saveData");
        ElMessage.success("保存成功");
      } else if (command === "run") {
        run();
      } else if (command === "stop") {
        stop();
      } else if (command === "copy") {
        context.emit("copyNode");
      } else if (command === "paste") {
        context.emit("pasteNode");
      } else if (command === "del") {
        context.emit("deleteNode");
      }
    };

    return {
      handle
    }
  }
};
</script>

<style lang="less" scoped>
.toolbar {
  text-align: right;
  width: 100%;
  padding: 8px 0;
  border-top: 1px solid #ccc;
  border-left: 1px solid #ccc;
  border-right: 1px solid #ccc;
  box-shadow: 0 8px 12px 0 rgba(0, 52, 107, 0.04);

  .command {
    display: inline-block;
    margin: 0 6px;
    line-height: 27px;
    border: 1px solid rgba(2, 2, 2, 0);
    border-radius: 2px;

    span {
      margin: 0 6px;
    }

    &:nth-of-type(1) {
      margin-left: 24px;
    }

    &:hover {
      border: 1px solid #E9E9E9;
      cursor: pointer;
    }
  }

  .separator {
    margin: 4px;
    border-left: 2px solid #e4e4e4;
  }
}
</style>
