// flow-eda-vue/src/components/editor/NodeDetail.vue
<template>
  <div v-click-outside="hideDetail" class="node-detail">
    <div class="detail-header">
      <div class="title">{{ node.nodeType.typeName }}</div>
      <el-button class="button el-button--small" style="float: right" type="primary" @click="submitNode(detailFormRef)">
        保存
      </el-button>
    </div>
    <div class="detail-body">
      <div v-if="node.output" class="item">
        <json-viewer :expand-depth=3 :value="node.output" copyable/>
        <hr/>
      </div>
      <el-form ref="detailFormRef" :model="detailForm" :rules="rules" class="row" label-position="top">
        <el-form-item class="item" label="名称：" prop="name">
          <el-input v-model="detailForm.name" class="input"/>
        </el-form-item>
        <el-form-item v-for="p in node.nodeType.params" :id="p.key" :key="p.key" :label="p.name+'：'" :prop="p.key"
                      class="item">
          <el-input v-if="p.inType==='input'" v-model="detailForm[p.key]" :placeholder="p.placeholder" class="input"/>
          <el-input v-if="p.inType==='select' && p.placeholder" v-model="detailForm[p.key]"
                    :placeholder="p.placeholder.split(',')[0]"
                    class="input-left"/>
          <el-select v-if="p.inType==='select' && p.placeholder" v-model="detailForm[p.key+'-o']" class="input-right">
            <el-option v-for="op in p.option.split(',')" :key="op" :label="op" :value="op"></el-option>
          </el-select>
          <el-select v-if="p.inType==='select' && !p.placeholder" v-model="detailForm[p.key]" class="input">
            <el-option v-for="op in p.option.split(',')" :key="op" :label="op" :value="op"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item class="item" prop="payload">
          <span class="span-box">
              <el-tooltip content="参数为json格式，可传递至下一节点，使用${xx}接收，例如${a,httpResult.$0.name}"
                          placement="top">
                <i class="el-icon-question" style="color: #c0c4cc;"></i>
              </el-tooltip>
              <span style="color: #606266;"> 自定义参数：</span>
            </span>
          <el-input v-model="detailForm.payload" autosize="" class="input" placeholder="{'a':'xx','b':'123'}"
                    type="textarea"/>
        </el-form-item>
        <el-form-item class="item" label="备注：" prop="remark">
          <el-input v-model="detailForm.remark" autosize="" class="input" type="textarea"/>
        </el-form-item>
      </el-form>
    </div>
  </div>
</template>

<script>
import {reactive, ref} from "vue";
import vClickOutside from 'click-outside-vue3'
import {ElMessage} from "element-plus";
import JsonViewer from 'vue-json-viewer';

export default {
  name: "NodeDetail",
  props: {
    node: Object
  },
  components: {
    JsonViewer
  },
  directives: {
    clickOutside: vClickOutside.directive
  },
  setup(props, context) {
    // 节点参数定义
    const ps = props.node.nodeType.params;
    // 节点参数数据
    const pv = props.node.params;
    // 表单参数数据
    const form = {name: props.node.nodeName, remark: props.node.remark};
    if (props.node.payload) {
      form.payload = JSON.stringify(props.node.payload);
    }
    if (pv) {
      Object.keys(pv).forEach(k => form[k] = pv[k]);
    }
    const detailForm = reactive(form);
    const detailFormRef = ref(null);

    // 校验输入的字符串是否是json格式
    const checkJson = (rule, value, callback) => {
      if (!value) {
        callback();
      }
      if (value.startsWith("{") && value.endsWith("}")) {
        try {
          JSON.parse(value);
          callback();
        } catch (ignore) {
        }
      }
      callback(new Error("Please input json format!"))
    };

    // 表单校验规则
    const ruleForm = {
      name: [{required: true, trigger: 'blur'}],
      payload: [{validator: checkJson, trigger: 'blur'}]
    };
    if (ps && ps.length > 0) {
      ps.forEach(p => {
        // 处理输入框+选择框=单个参数的情况，需要在form中拆成两个参数
        if (p.inType === 'select' && p.placeholder) {
          if (form[p.key]) {
            form[p.key + '-o'] = form[p.key].split(',')[1];
            form[p.key] = form[p.key].split(',')[0];
          } else {
            form[p.key + '-o'] = p.placeholder.split(',')[1];
          }
        }
        // 参数必填规则
        if (p.required === true) {
          ruleForm[p.key] = [{required: true, trigger: 'blur'}]
        }
      });
    }
    const rules = reactive(ruleForm);

    const hideDetail = () => {
      context.emit("showNodeDetail", props.node, false);
    };

    // 提交表单节点信息
    const submitNode = (formEl) => {
      formEl.validate((valid) => {
        if (valid) {
          // 将节点信息和节点属性信息封装好传给编辑器
          let params = {};
          Object.keys(detailForm).forEach(k => {
            if (k !== 'name' && k !== 'remark' && k !== 'payload'
                && detailForm[k] && detailForm[k] !== null) {
              if (detailForm[k + '-o']) {
                params[k] = detailForm[k] + ',' + detailForm[k + '-o'];
              } else if (!k.endsWith('-o')) {
                params[k] = detailForm[k];
              }
            }
          });
          props.node.nodeName = detailForm.name;
          if (detailForm.remark) {
            props.node.remark = detailForm.remark;
          }
          if (detailForm.payload) {
            props.node.payload = JSON.parse(detailForm.payload);
          }
          if (Object.keys(params).length === 0) {
            params = undefined;
          }
          context.emit("updateNode", props.node, params);
          ElMessage.success("保存成功");
        }
      });
    };

    return {
      detailForm,
      rules,
      detailFormRef,
      hideDetail,
      submitNode
    };
  }
};
</script>

<style lang="less">
.node-detail {
  height: 100%;
  overflow: auto;
  background: #ffffff;
  flex: 0 0 auto;
  float: left;
  width: 28%;
  border-right: 1px solid #E9E9E9;
  border-bottom: 1px solid #E9E9E9;

  .detail-header {
    padding: 12px 12px 10px 12px;
    min-height: 32px;
    border-bottom: 1px solid #DCE3E8;

    .title {
      float: left;
      font-size: 18px;
      text-align: center;
      line-height: 32px;
    }

    .button {
      font-size: 14px;
      padding: 7px 15px
    }
  }

  .detail-body {
    .row {
      padding: 8px 8px 8px 14px;

      .item {
        margin-bottom: 12px;
      }

      .input {
        width: 100%;
      }

      .input-left {
        float: left;
        width: 50%;
      }

      .input-right {
        float: right;
        width: 50%;
      }
    }
  }
}
</style>

// flow-eda-react/src/pages/FlowEditor/NodeDetail/index.tsx
import React, { useEffect } from 'react';
import './index.less';
import { Button, Form, Input, Select } from 'antd';
const { Option } = Select;
import ReactJson from 'react-json-view';

const FlowDetail: React.FC<{
  node: API.Node;
  updateNode: (node: API.Node, params: object) => void;
}> = (props) => {
  const [form] = Form.useForm();

  /** 根据节点信息初始化表单内容*/
  useEffect(() => {
    const detail = { name: props.node.nodeName, remark: props.node.remark };
    if (props.node.payload) {
      // @ts-ignore
      detail.payload = JSON.stringify(props.node.payload);
    }
    const pv = props.node.params;
    if (pv) {
      Object.keys(pv).forEach((k) => (detail[k] = pv[k]));
    }
    const ps = props.node.nodeType?.params;
    if (ps && ps.length > 0) {
      ps.forEach((p) => {
        // 处理输入框+选择框=单个参数的情况，需要在form中拆成两个参数
        if (p.inType === 'select' && p.placeholder) {
          if (detail[p.key]) {
            detail[p.key + '-o'] = detail[p.key].split(',')[1];
            detail[p.key] = detail[p.key].split(',')[0];
          } else {
            detail[p.key + '-o'] = p.placeholder.split(',')[1];
          }
        }
      });
    }
    form.setFieldsValue(detail);
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  /** 校验json格式 */
  const checkJson = (rule: any, value: string, callback: (error?: string) => void) => {
    if (value) {
      if (value.startsWith('{') && value.endsWith('}')) {
        try {
          JSON.parse(value);
          callback();
        } catch (ignore) {}
      }
      callback('Please input json format!');
    }
    callback();
  };

  /** 提交表单，更新节点信息 */
  const onFinish = (values: any) => {
    const newNode = JSON.parse(JSON.stringify(props.node));
    newNode.nodeName = values.name;
    if (values.remark) {
      newNode.remark = values.remark;
    }
    if (values.payload) {
      newNode.payload = JSON.parse(values.payload);
    } else {
      newNode.payload = null;
    }
    let params: any = {};
    Object.keys(values).forEach((k) => {
      if (k !== 'name' && k !== 'remark' && k !== 'payload' && values[k] !== null) {
        if (values[k + '-o']) {
          params[k] = values[k] + ',' + values[k + '-o'];
        } else if (!k.endsWith('-o')) {
          params[k] = values[k];
        }
      }
    });
    if (Object.keys(params).length === 0) {
      params = undefined;
    }
    props.updateNode(newNode, params);
  };

  return (
    <div className="node-detail">
      <div className="detail-header">
        <div className="title">{props.node.nodeType?.typeName}</div>
        <Button
          type="primary"
          className="button"
          style={{ float: 'right' }}
          onClick={form.submit}
          htmlType="submit"
        >
          保存
        </Button>
      </div>
      <div className="detail-body">
        {props.node.output && (
          <div className="item">
            {/* @ts-ignore */}
            <ReactJson
              src={props.node.output}
              collapsed={3}
              name={false}
              displayDataTypes={false}
              displayObjectSize={false}
              quotesOnKeys={false}
              style={{ fontFamily: 'consolas', backgroundColor: '#ffffff' }}
            />
            <hr />
          </div>
        )}

        <Form form={form} className="row" layout="vertical" onFinish={onFinish}>
          <Form.Item className="item" label="名称：" name="name" rules={[{ required: true }]}>
            <Input className="input" />
          </Form.Item>
          {props.node.nodeType?.params?.map((p) => {
            return (
              <div key={p.key}>
                {p.inType === 'input' && (
                  <Form.Item
                    label={p.name + '：'}
                    className="item"
                    name={p.key}
                    key={p.key}
                    rules={[{ required: p.required }]}
                  >
                    <Input placeholder={p.placeholder} className="input" />
                  </Form.Item>
                )}
                {p.inType === 'select' && p.placeholder && (
                  <Form.Item
                    label={p.name + '：'}
                    key={p.key}
                    className="item"
                    required={p.required}
                  >
                    <Input.Group compact>
                      <Form.Item name={p.key} noStyle rules={[{ required: p.required }]}>
                        <Input placeholder={p.placeholder.split(',')[0]} className="input-left" />
                      </Form.Item>
                      <Form.Item name={p.key + '-o'} noStyle rules={[{ required: p.required }]}>
                        <Select className="input-right">
                          {p.option?.split(',')?.map((op: string) => {
                            return (
                              <Option value={op} key={op}>
                                {op}
                              </Option>
                            );
                          })}
                        </Select>
                      </Form.Item>
                    </Input.Group>
                  </Form.Item>
                )}
                {p.inType === 'select' && !p.placeholder && (
                  <Form.Item
                    label={p.name + '：'}
                    className="item"
                    name={p.key}
                    key={p.key}
                    rules={[{ required: p.required }]}
                  >
                    <Select className="input">
                      {p.option?.split(',')?.map((op: string) => {
                        return (
                          <Option value={op} key={op}>
                            {op}
                          </Option>
                        );
                      })}
                    </Select>
                  </Form.Item>
                )}
              </div>
            );
          })}

          <Form.Item
            className="item"
            name="payload"
            label="自定义参数："
            tooltip="参数为json格式，可传递至下一节点，使用${xx}接收，例如${a,httpResult.$0.name}"
            rules={[{ validator: checkJson }]}
          >
            <Input.TextArea autoSize={true} className="input" placeholder="{'a':'xx','b':'123'}" />
          </Form.Item>
          <Form.Item className="item" label="备注：" name="remark">
            <Input.TextArea autoSize={true} className="input" />
          </Form.Item>
        </Form>
      </div>
    </div>
  );
};

export default FlowDetail;
